<?php

namespace App\Doctrine;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $num
     *
     * @return \App\Doctrine\User[]
     */
    public function getLastUser(int $num)
    {
        $query = $this->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults($num)
            ->getQuery();
        return $query->getResult();
    }
}
